---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: eks-nodegroup-updater
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: amazon/aws-cli
              imagePullPolicy: IfNotPresent
              command:
                - /app/eks-nodegroup-updater
              volumeMounts:
                - name: script
                  mountPath: "/app/"
              args:
          env:
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: target
                  key: CLUSTER_NAME
            - name: NODEGROUP_NAMES
              valueFrom:
                configMapKeyRef:
                  name: target
                  key: NODEGROUP_NAMES
                  optional: true
          volumes:
            - name: script
              configMap:
                name: script
                defaultMode: 0555
                items:
                  - key: script
                    path: eks-nodegroup-updater
          restartPolicy: Never
